/**
 * The Ralph loop, driven by a Linear agent session:
 *
 *   load epic -> prepare worktree -> repeat { pick next ready story -> fresh agent session ->
 *   check <promise>COMPLETE</promise> -> run verify commands -> commit/push/PR -> mark story Done }
 *
 * Linear child issues are the tracker (like ralph-tui's Linear tracker), the agent session is the
 * activity log, and the session plan shows story checklist progress.
 */
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { ActivityReporter } from "../agent/activity.js";
import { type AgentRunner, requestSystemAppend } from "../agent/runner.js";
import type { Config, RepositoryConfig } from "../config.js";
import type { CommandResult, Forge, GitWorkspace } from "../git/workspace.js";
import { type LoadedEpic, loadEpic, openRootBlockers } from "../linear/epic-loader.js";
import {
	type AttachmentEntry,
	type AttachmentFetcher,
	type AttachmentSource,
	attachmentsForStory,
	collectAttachments,
	formatAttachments,
} from "../linear/attachments.js";
import type { IssueSummary, LinearGateway, PlanStep } from "../linear/gateway.js";
import type { Logger } from "../logger.js";
import { ensureProgressFile, extractCodebasePatterns, readProgress, recentProgressEntries } from "../ralph/progress.js";
import { COMPLETE_PATTERN, DEFAULT_STORY_TEMPLATE, buildRequestPrompt, buildStoryPrompt } from "../ralph/prompt.js";
import { blockedStories, isEpicComplete, isStoryDone, selectNextStory } from "../ralph/selection.js";
import { type Epic, type Story, dependencyLabel, externalIdOf } from "../ralph/types.js";
import { describeRouting, routeIssue, selectionValue } from "./routing.js";
import type { SessionRecord, SessionStatus } from "./store.js";

export interface EngineDeps {
	config: Config;
	linear: LinearGateway;
	runner: AgentRunner;
	git: GitWorkspace;
	shell: (command: string, cwd: string) => Promise<CommandResult>;
	log: Logger;
	/** Downloads Linear uploads (screenshots etc.) for prompts; omitted = attachments aren't fetched. */
	attachments?: AttachmentFetcher;
}

export interface EngineRun {
	record: SessionRecord;
	reporter: ActivityReporter;
	abortSignal: AbortSignal;
	/** Persist the record (called after every state change). */
	persist: () => Promise<void>;
	/** Reserve the worktree for this run; false if another live session is using it. */
	claimWorktree?: (path: string) => boolean;
	/** Linear uploads gathered for this run (set by the engine). */
	attachments?: AttachmentEntry[];
	/** Receives the live session's message injector while an agent session runs. */
	setInjector?: (inject: ((text: string) => boolean) | undefined) => void;
}

const MAX_FEEDBACK = 6000;

function tail(text: string, n: number): string {
	return text.length > n ? `…${text.slice(-n)}` : text;
}

function quote(text: string): string {
	return text
		.trim()
		.split("\n")
		.map((l) => `> ${l}`)
		.join("\n");
}

export function planFor(epic: Epic, current?: Story, exhausted: ReadonlySet<string> = new Set()): PlanStep[] {
	return epic.stories.map((s) => ({
		content: `${s.storyId}: ${s.title}`,
		status:
			s.status === "completed"
				? "completed"
				: s.status === "cancelled" || exhausted.has(s.key)
					? "canceled"
					: current?.key === s.key
						? "inProgress"
						: "pending",
	}));
}

export function prBody(epic: Epic): string {
	const lines = [
		`Implements Linear epic **${epic.identifier}: ${epic.title}**${epic.url ? ` (${epic.url})` : ""}, one story per commit.`,
		"",
		"### Stories",
		...epic.stories.map((s) => `- [${s.status === "completed" ? "x" : " "}] ${s.storyId}: ${s.title}${s.identifier && s.identifier !== s.storyId ? ` (${s.identifier})` : ""}`),
		"",
		"_Generated by cyralph (Ralph loop on Linear)._",
	];
	return lines.join("\n");
}

/** "Merge request" for GitLab URLs, "Pull request" otherwise. */
export function prLabel(url: string): string {
	return /\/-\/merge_requests\//.test(url) ? "Merge request" : "Pull request";
}

export class EpicEngine {
	/** Sessions that already reported why a PR/MR can't be opened (don't repeat it every story). */
	private readonly forgeProblems = new Set<string>();

	constructor(private readonly deps: EngineDeps) {}

	async run(ctx: EngineRun): Promise<SessionStatus> {
		const { config, linear, log } = this.deps;
		const { record, reporter } = ctx;

		let loaded: LoadedEpic;
		try {
			// A mention only reads the epic for context; it never creates story issues.
			const materializeStories = record.mode === "epic" && config.ralph.materializeStories;
			loaded = await loadEpic(linear, record.issueId, { materializeStories });
		} catch (err) {
			await reporter.error(`Could not load the issue from Linear: ${String(err)}`);
			return "failed";
		}
		const { epic } = loaded;
		record.identifier = epic.identifier;
		record.focusStoryKey ??= loaded.focusStoryKey;
		for (const s of epic.stories) if (record.completedKeys.includes(s.key)) s.status = "completed";

		if (record.mode === "request") return this.runRequestOnly(ctx, epic);

		let rootBlockers: Array<{ id: string; identifier: string }> = [];
		if (record.ignoreBlockers) {
			// A human said to go ahead: outside blockers no longer gate any story.
			for (const s of epic.stories) s.dependsOn = s.dependsOn.filter((d) => !externalIdOf(d));
		} else {
			// Blocked-by on the epic (or plain issue) itself gates the story work, as in Cyrus.
			rootBlockers = await openRootBlockers(linear, epic);
			// Direct requests (e.g. "push and open a PR") aren't story work, so they still run.
			if (rootBlockers.length > 0 && record.pendingRequests.length === 0) {
				return this.park(ctx, epic, rootBlockers, `**${epic.identifier}** is blocked`);
			}
		}
		record.waitingOn = [];

		const issue = await linear.getIssue(epic.issueId);
		const repo = await this.resolveRepo(ctx, issue);
		if (!repo) return "awaiting_input";

		await reporter.thought(this.describeEpic(epic, loaded, repo, record.routedBy));

		const worktree = await this.prepareWorkspace(ctx, epic, repo);
		if (typeof worktree !== "string") return worktree.status;

		const progressFile = join(config.stateDir, "epics", epic.identifier, "progress.md");
		await ensureProgressFile(progressFile, `${epic.identifier}: ${epic.title}`);
		await this.gatherAttachments(ctx, epic);

		if (rootBlockers.length > 0) {
			const requestOutput = await this.runRequests({ ctx, epic, repo, worktree, progressFile });
			if (requestOutput) await reporter.thought(requestOutput);
			await this.adoptPullRequest(ctx, repo, worktree);
			return this.park(ctx, epic, rootBlockers, `**${epic.identifier}** is still blocked`);
		}

		const template = repo.promptTemplatePath ? await readFile(repo.promptTemplatePath, "utf8") : DEFAULT_STORY_TEMPLATE;
		const verifyCommands = [...(repo.verifyCommands ?? []), ...(repo.runPrdQualityGates ? epic.qualityGates : [])];

		if (!["started", "completed"].includes(issue.stateType)) {
			await linear.setIssueState(epic.issueId, { type: "started" }).catch((e: unknown) => log.warn(String(e)));
		}

		// Which stories this run may touch.
		const inScope = (s: Story) => !record.focusStoryKey || s.key === record.focusStoryKey;
		const exhausted = () =>
			new Set(epic.stories.filter((s) => (record.attempts[s.key] ?? 0) >= config.ralph.maxAttemptsPerStory).map((s) => s.key));
		const outOfScope = new Set(epic.stories.filter((s) => !inScope(s)).map((s) => s.key));

		await reporter.plan(planFor(epic, undefined, exhausted()));

		let iterations = 0;
		const cap = config.ralph.maxIterationsPerRun;
		while (!ctx.abortSignal.aborted) {
			if (cap > 0 && iterations >= cap) break;
			const skip = new Set([...exhausted(), ...outOfScope]);
			const story = selectNextStory(epic.stories, skip);
			if (!story) break;
			iterations++;
			await this.runStory({ ctx, epic, story, repo, worktree, progressFile, template, verifyCommands, exhausted });
		}

		// Instructions no story iteration picked up (e.g. "push and open a PR" on a finished epic)
		// run as a direct request, the way Cyrus handles an @mention.
		const requestOutput = ctx.abortSignal.aborted
			? undefined
			: await this.runRequests({ ctx, epic, repo, worktree, progressFile });

		return this.finish({ ctx, epic, repo, worktree, inScope, exhausted: exhausted(), hitCap: cap > 0 && iterations >= cap, requestOutput });
	}

	/**
	 * The repository for this session (Cyrus routing: tags, labels, project, team, catch-all). Sticky once
	 * chosen. Returns undefined after asking the user to pick one when nothing matches.
	 */
	private async resolveRepo(ctx: EngineRun, epicIssue: IssueSummary): Promise<RepositoryConfig | undefined> {
		const { record, reporter } = ctx;
		const repos = this.deps.config.repositories;
		const withBase = (r: RepositoryConfig) => (record.baseBranchOverride ? { ...r, baseBranch: record.baseBranchOverride } : r);
		const sticky = record.repoId && repos.find((r) => r.id === record.repoId);
		if (sticky) return withBase(sticky);

		// The delegated issue first (a story may carry its own tag/labels), then its epic.
		const delegated = record.issueId === epicIssue.id ? epicIssue : await this.deps.linear.getIssue(record.issueId);
		const issues = delegated.id === epicIssue.id ? [epicIssue] : [delegated, epicIssue];
		const routed = routeIssue(repos, issues);
		if (routed.type === "needs_selection") {
			record.repoSelection = routed.candidates.map((r) => r.id);
			await ctx.persist();
			await reporter.select(
				"Which repository should I work in for this issue?\n\n(Add a `[repo=name]` tag, a routing label, or team/project routing in the config to skip this next time.)",
				routed.candidates.map(selectionValue),
			);
			return undefined;
		}
		record.repoId = routed.repo.id;
		record.routedBy = describeRouting(routed);
		record.baseBranchOverride = routed.baseBranch;
		await ctx.persist();
		return withBase(routed.repo);
	}

	/** Create/reuse the epic's worktree. Returns its path, or the status to end the run with. */
	private async prepareWorkspace(ctx: EngineRun, epic: Epic, repo: RepositoryConfig): Promise<string | { status: SessionStatus }> {
		const { config } = this.deps;
		const { record, reporter } = ctx;
		try {
			const ws = await this.deps.git.prepare({
				repositoryPath: repo.repositoryPath,
				workspaceBaseDir: repo.workspaceBaseDir ?? join(config.stateDir, "worktrees", repo.id),
				branch: record.branch ?? epic.branchName,
				baseBranch: repo.baseBranch,
			});
			if (ctx.claimWorktree && !ctx.claimWorktree(ws.path)) {
				await reporter.elicitation(
					`Another cyralph session is already working on \`${ws.branch}\`. Reply here once it finishes and I'll pick up.`,
				);
				return { status: "awaiting_input" };
			}
			record.branch = ws.branch;
			record.worktreePath = ws.path;
			await ctx.persist();
			if (ws.created && repo.setupCommand) {
				await reporter.action("Setup", repo.setupCommand);
				const r = await this.deps.shell(repo.setupCommand, ws.path);
				if (r.code !== 0) await reporter.thought(`Setup command failed (continuing):\n\n\`\`\`\n${tail(r.stderr || r.stdout, 2000)}\n\`\`\``);
			}
			return ws.path;
		} catch (err) {
			await reporter.error(`Could not prepare the git worktree: ${String(err)}`);
			return { status: "failed" };
		}
	}

	/**
	 * An @mention: like Cyrus, act only on what the comment asks, with the epic as context. No story
	 * loop, no Linear state changes, and blockers don't apply. `/ralph` in the comment opts into the loop.
	 */
	private async runRequestOnly(ctx: EngineRun, epic: Epic): Promise<SessionStatus> {
		const { config, linear } = this.deps;
		const { record, reporter } = ctx;
		if (record.pendingRequests.length === 0) {
			await reporter.response("Nothing to do: the mention didn't include a request. Delegate the issue to me to work the epic.");
			return "completed";
		}
		const repo = await this.resolveRepo(ctx, await linear.getIssue(epic.issueId));
		if (!repo) return "awaiting_input";
		const worktree = await this.prepareWorkspace(ctx, epic, repo);
		if (typeof worktree !== "string") return worktree.status;
		const progressFile = join(config.stateDir, "epics", epic.identifier, "progress.md");
		await ensureProgressFile(progressFile, `${epic.identifier}: ${epic.title}`);
		await this.gatherAttachments(ctx, epic);

		const output = await this.runRequests({ ctx, epic, repo, worktree, progressFile });
		if (ctx.abortSignal.aborted) {
			await reporter.response("Stopped.");
			return "stopped";
		}
		await this.adoptPullRequest(ctx, repo, worktree);
		const link = record.prUrl && output && !output.includes(record.prUrl) ? `\n\n${prLabel(record.prUrl)}: ${record.prUrl}` : "";
		await reporter.response(`${output ?? "Done."}${link}`);
		return "completed";
	}

	/** Run pending thread requests as one direct agent session. Returns its summary for the thread. */
	private async runRequests(args: { ctx: EngineRun; epic: Epic; repo: RepositoryConfig; worktree: string; progressFile: string }): Promise<string | undefined> {
		const { ctx, epic, repo, worktree, progressFile } = args;
		const { config, runner, git } = this.deps;
		const { record, reporter } = ctx;
		const requests = [...record.pendingRequests];
		if (requests.length === 0) return undefined;

		await reporter.thought(requests.length === 1 ? "Working on your request." : `Working on your ${requests.length} requests.`);
		const branch = record.branch ?? epic.branchName;
		const forge = await this.forgeFor(worktree, repo);
		const historyRewrite = repo.historyRewrite ?? config.ralph.historyRewrite;
		const prompt = buildRequestPrompt({
			epic,
			requests,
			historyRewrite,
			branch,
			baseBranch: repo.baseBranch,
			remoteUrl: await git.remoteUrl(worktree),
			prUrl: record.prUrl,
			progressFile,
			qualityGates: [...epic.qualityGates, ...(repo.verifyCommands ?? [])],
			forgeInstructions: forge?.agentInstructions({
				branch,
				baseBranch: repo.baseBranch,
				title: `${epic.identifier}: ${epic.title.replace(/"/g, "'")}`,
			}),
			prTerm: forge?.term,
			attachments: formatAttachments(ctx.attachments ?? []),
		});
		const runOnce = (resume?: string) =>
			runner.run({
				prompt,
				cwd: worktree,
				additionalDirectories: this.agentDirs(progressFile, epic),
				model: repo.model ?? config.model,
				fallbackModel: config.fallbackModel,
				allowedTools: repo.allowedTools,
				disallowedTools: repo.disallowedTools,
				permissionMode: config.permissionMode,
				abortSignal: ctx.abortSignal,
				onEvent: reporter.onRunnerEvent,
				onInjector: ctx.setInjector,
				systemAppend: requestSystemAppend(historyRewrite),
				resume,
			});
		// Follow-ups continue the previous request conversation, like Cyrus resuming its Claude session.
		let result = await runOnce(record.requestClaudeSessionId);
		if (result.isError && record.requestClaudeSessionId && !result.sessionId && !ctx.abortSignal.aborted) {
			this.deps.log.warn(`could not resume request session ${record.requestClaudeSessionId}; starting fresh`);
			result = await runOnce(undefined);
		}
		if (result.sessionId) record.requestClaudeSessionId = result.sessionId;
		record.totalCostUsd += result.costUsd ?? 0;
		if (result.aborted) return undefined; // keep the requests pending for the next run
		record.pendingRequests = record.pendingRequests.filter((r) => !requests.includes(r));
		await ctx.persist();
		if (result.isError) return `I ran into an error working on your request (${result.errorMessage ?? "unknown error"}).\n\n${tail(result.output, 2000)}`.trim();
		return result.output.trim() || "Done.";
	}

	private attachmentsDir(epic: Epic): string {
		return join(this.deps.config.stateDir, "attachments", epic.identifier);
	}

	/** Extra directories the agent may read: the progress log and downloaded attachments. */
	private agentDirs(progressFile: string, epic: Epic): string[] {
		return [join(progressFile, ".."), ...(this.deps.attachments ? [this.attachmentsDir(epic)] : [])];
	}

	/**
	 * Download files uploaded to Linear (pasted screenshots, mockups, PDFs) referenced by the epic, its
	 * stories, their comments, and the session thread, so prompts can point the agent at local copies.
	 */
	private async gatherAttachments(ctx: EngineRun, epic: Epic): Promise<void> {
		const fetcher = this.deps.attachments;
		if (!fetcher) return;
		const { linear, log } = this.deps;
		const { record, reporter } = ctx;
		const sources: AttachmentSource[] = [{ label: `${epic.identifier} description`, text: epic.description }];
		const comments = async (issueId: string) => linear.getComments(issueId).catch((e: unknown) => (log.warn(`comments for ${issueId}: ${String(e)}`), []));
		for (const c of await comments(epic.issueId)) sources.push({ label: `comment on ${epic.identifier}${c.author ? ` by ${c.author}` : ""}`, text: c.body });
		for (const s of epic.stories) {
			if (!s.issueId || s.issueId === epic.issueId) continue;
			sources.push({ label: s.storyId, text: s.sourceText ?? s.description, storyKey: s.key });
			if (s.status === "completed" || s.status === "cancelled") continue;
			for (const c of await comments(s.issueId)) sources.push({ label: `comment on ${s.storyId}${c.author ? ` by ${c.author}` : ""}`, text: c.body, storyKey: s.key });
		}
		for (const t of [...record.guidance, ...record.pendingRequests]) sources.push({ label: "Linear thread", text: t });

		const entries = await collectAttachments({ sources, dir: this.attachmentsDir(epic), fetcher }).catch((e: unknown) => {
			log.warn(`attachment download failed: ${String(e)}`);
			return [] as AttachmentEntry[];
		});
		ctx.attachments = entries;
		const failed = entries.filter((e) => !e.path);
		if (failed.length > 0) {
			await reporter.thought(
				`I couldn't download ${failed.length} of ${entries.length} attachment(s) from Linear, so I can't see them:\n\n${failed
					.map((e) => `- ${e.title ?? e.url} (${e.sources.join(", ")}): ${e.error}`)
					.join("\n")}`,
			);
		} else if (entries.length > 0) {
			log.info(`${epic.identifier}: ${entries.length} attachment(s) available`);
		}
	}

	/** GitHub (`gh`) or GitLab (`glab`) for this repo's `origin`; undefined without a remote. */
	private forgeFor(worktree: string, repo: RepositoryConfig): Promise<Forge | undefined> {
		return this.deps.git.forge(worktree, { forge: repo.forge, gitlabHost: repo.gitlabHost, gitlabHosts: this.deps.config.gitlabHosts });
	}

	/** Pick up a PR/MR the agent opened itself (e.g. via a direct request) so the session links it. Never opens one. */
	private async adoptPullRequest(ctx: EngineRun, repo: RepositoryConfig, worktree: string): Promise<void> {
		const { record, reporter } = ctx;
		if (record.prUrl || !record.branch) return;
		const forge = await this.forgeFor(worktree, repo);
		const pr = forge ? await forge.find(worktree, record.branch).catch(() => undefined) : undefined;
		if (!pr) return;
		record.prUrl = pr.url;
		record.prNumber = pr.number;
		await ctx.persist();
		await reporter.externalUrl(prLabel(record.prUrl), pr.url);
	}

	private describeEpic(epic: Epic, loaded: LoadedEpic, repo: RepositoryConfig, routedBy?: string): string {
		const done = epic.stories.filter(isStoryDone).length;
		const kind =
			epic.kind === "single"
				? "a single issue (no PRD structure found), so I'll treat it as one story"
				: `a Ralph epic with ${epic.stories.length} stories (${done} already done)`;
		const via = routedBy ? ` (routed by ${routedBy})` : "";
		const lines = [`**${epic.identifier}** is ${kind}. Working in \`${repo.name}\`${via} on branch \`${epic.branchName}\`, based on \`${repo.baseBranch}\`.`];
		if (loaded.materialized > 0) lines.push(`Created ${loaded.materialized} story sub-issues from the PRD in the description.`);
		if (loaded.focusStoryKey) {
			const s = epic.stories.find((x) => x.key === loaded.focusStoryKey);
			lines.push(`This issue is one story of the epic, so I'll only work on ${s?.storyId ?? "it"}.`);
		}
		if (epic.qualityGates.length) lines.push(`Quality gates: ${epic.qualityGates.map((g) => `\`${g}\``).join(", ")}`);
		return lines.join("\n\n");
	}

	private async runStory(args: {
		ctx: EngineRun;
		epic: Epic;
		story: Story;
		repo: RepositoryConfig;
		worktree: string;
		progressFile: string;
		template: string;
		verifyCommands: string[];
		exhausted: () => Set<string>;
	}): Promise<void> {
		const { ctx, epic, story, repo, worktree, progressFile, template, verifyCommands } = args;
		const { config, linear, runner, log } = this.deps;
		const { record, reporter } = ctx;
		const max = config.ralph.maxAttemptsPerStory;
		const attempt = (record.attempts[story.key] ?? 0) + 1;
		record.attempts[story.key] = attempt;
		await ctx.persist();

		if (story.issueId && epic.kind !== "single" && story.status === "open") {
			await linear.setIssueState(story.issueId, { type: "started" }).catch((e: unknown) => log.warn(String(e)));
		}
		story.status = "in_progress";
		await reporter.plan(planFor(epic, story, args.exhausted()));
		await reporter.thought(`▶️ **${story.storyId}: ${story.title}** (attempt ${attempt}/${max})`);

		const pendingAtStart = [...record.pendingRequests];
		const progress = await readProgress(progressFile);
		const prompt = buildStoryPrompt(
			{
				epic,
				story,
				progressFile,
				codebasePatterns: extractCodebasePatterns(progress),
				recentProgress: recentProgressEntries(progress, 5),
				previousAttemptFeedback: record.lastFeedback[story.key],
				guidance: record.guidance.slice(-10),
				attempt,
				maxAttempts: max,
				appendInstruction: repo.appendInstruction,
				attachments: formatAttachments(attachmentsForStory(ctx.attachments ?? [], story.key)),
			},
			template,
		);

		const result = await runner.run({
			prompt,
			cwd: worktree,
			additionalDirectories: this.agentDirs(progressFile, epic),
			model: repo.model ?? config.model,
			fallbackModel: config.fallbackModel,
			allowedTools: repo.allowedTools,
			disallowedTools: repo.disallowedTools,
			permissionMode: config.permissionMode,
			abortSignal: ctx.abortSignal,
			onEvent: reporter.onRunnerEvent,
			onInjector: ctx.setInjector,
		});
		record.totalCostUsd += result.costUsd ?? 0;
		if (!result.aborted) {
			// The story prompt carried these as guidance, so they've been acted on.
			record.pendingRequests = record.pendingRequests.filter((r) => !pendingAtStart.includes(r));
		}

		if (result.aborted) {
			record.attempts[story.key] = attempt - 1; // an interrupted attempt doesn't count
			await ctx.persist();
			return;
		}

		let feedback: string | undefined;
		if (result.isError) {
			feedback = `The agent session errored (${result.errorMessage ?? "unknown error"}). Last message:\n\n${quote(tail(result.output, 2000))}`;
		} else if (!COMPLETE_PATTERN.test(result.output)) {
			feedback = `The previous session ended without the completion signal. Its final message was:\n\n${quote(tail(result.output, 3000))}`;
		} else {
			for (const cmd of verifyCommands) {
				await reporter.action("Verify", cmd);
				const r = await this.deps.shell(cmd, worktree);
				await reporter.action("Verify", cmd, r.code === 0 ? "passed" : `failed (exit ${r.code})`);
				if (r.code !== 0) {
					feedback = `The agent signalled completion, but the verification command \`${cmd}\` failed (exit ${r.code}):\n\n\`\`\`\n${tail(`${r.stdout}\n${r.stderr}`.trim(), MAX_FEEDBACK)}\n\`\`\``;
					break;
				}
			}
		}

		if (feedback) {
			record.lastFeedback[story.key] = feedback;
			await ctx.persist();
			if (attempt >= max) {
				// Park the partial work so the next story starts from a clean tree.
				const stashed = await this.deps.git.stashAll(worktree, `cyralph: incomplete ${story.storyId} (${epic.identifier})`).catch(() => false);
				story.status = story.issueId ? "in_progress" : "open";
				await reporter.thought(
					`⚠️ ${story.storyId} did not complete after ${attempt} attempts; setting it aside${stashed ? " (partial work stashed)" : ""}.\n\n${feedback}`,
				);
			} else {
				await reporter.thought(`${story.storyId} attempt ${attempt} did not complete; retrying with feedback.\n\n${tail(feedback, 1500)}`);
			}
			await reporter.plan(planFor(epic, undefined, args.exhausted()));
			return;
		}

		await this.completeStory({ ctx, epic, story, worktree, repo, summary: result.output.replace(COMPLETE_PATTERN, "").trim() });
	}

	private async completeStory(args: { ctx: EngineRun; epic: Epic; story: Story; worktree: string; repo: RepositoryConfig; summary: string }) {
		const { ctx, epic, story, worktree, repo, summary } = args;
		const { config, linear, git, log } = this.deps;
		const { record, reporter } = ctx;

		let sha: string | undefined;
		if (config.ralph.commitPerStory) {
			const ref = story.identifier && story.identifier !== story.storyId ? ` [${story.identifier}]` : "";
			const subject = epic.kind === "single" ? `${epic.identifier}: ${story.title}` : `feat(${story.storyId}): ${story.title}${ref}`;
			sha = await git.commitAll(worktree, `${subject}\n\nEpic: ${epic.identifier} ${epic.title}`).catch(async (e: unknown) => {
				await reporter.error(`Commit failed: ${String(e)}`);
				return undefined;
			});
		}

		story.status = "completed";
		delete record.lastFeedback[story.key];
		if (!story.issueId) record.completedKeys.push(story.key);
		await ctx.persist();

		if (story.issueId && epic.kind !== "single") {
			await linear.setIssueState(story.issueId, { type: "completed" }).catch((e: unknown) => log.warn(String(e)));
			const note = [`✅ Completed by cyralph${sha ? ` in \`${sha.slice(0, 10)}\`` : ""} on \`${record.branch}\`.`, "", tail(summary, 4000)].join("\n");
			await linear.addComment(story.issueId, note).catch((e: unknown) => log.warn(String(e)));
		}

		// No remote yet is fine: commits stay local and are pushed once `origin` exists.
		if (sha && config.ralph.pushPerStory && record.branch && (await git.remoteUrl(worktree))) {
			try {
				await git.push(worktree, record.branch);
				await this.syncPullRequest(ctx, epic, repo, worktree, false);
			} catch (err) {
				await reporter.error(`Push failed: ${String(err)}`);
			}
		}
		const done = epic.stories.filter(isStoryDone).length;
		await reporter.thought(`✅ **${story.storyId}** complete${sha ? ` (\`${sha.slice(0, 10)}\`)` : ""}. ${done}/${epic.stories.length} stories done.`);
	}

	private async syncPullRequest(ctx: EngineRun, epic: Epic, repo: RepositoryConfig, worktree: string, ready: boolean) {
		const { config } = this.deps;
		const { record, reporter } = ctx;
		if (!config.ralph.createPullRequest || !record.branch) return;
		const forge = await this.forgeFor(worktree, repo);
		if (!forge) return; // no remote to open a PR/MR against yet
		const body = prBody(epic);
		if (!record.prUrl) {
			// Say why there is no PR/MR instead of silently skipping it (once per run).
			if (!this.forgeProblems.has(record.sessionId)) {
				const problem = await forge.preflight(worktree);
				if (problem) {
					this.forgeProblems.add(record.sessionId);
					await reporter.thought(`Commits are pushed to \`${record.branch}\`, but I can't open a ${forge.term}: ${problem}`);
					return;
				}
			} else return;
			let pr: { url: string; number?: number };
			try {
				pr = await forge.ensure(worktree, { branch: record.branch, baseBranch: repo.baseBranch, title: `${epic.identifier}: ${epic.title}`, body });
			} catch (err) {
				this.forgeProblems.add(record.sessionId);
				await reporter.error(`Couldn't open a ${forge.term} with \`${forge.cli}\`: ${tail(String(err instanceof Error ? err.message : err), 1500)}`);
				return;
			}
			record.prUrl = pr.url;
			record.prNumber = pr.number;
			await ctx.persist();
			await reporter.externalUrl(prLabel(pr.url), pr.url);
			await reporter.thought(`Opened a draft ${forge.term}: ${pr.url}`);
		}
		await forge.update(worktree, { url: record.prUrl, number: record.prNumber }, { body, ready });
	}

	private async finish(args: {
		ctx: EngineRun;
		epic: Epic;
		repo: RepositoryConfig;
		worktree: string;
		inScope: (s: Story) => boolean;
		exhausted: Set<string>;
		hitCap: boolean;
		/** Summary from a direct request session, posted as the outcome. */
		requestOutput?: string;
	}): Promise<SessionStatus> {
		const { ctx, epic, repo, worktree, inScope, exhausted, hitCap, requestOutput } = args;
		const { config, linear, log } = this.deps;
		const { record, reporter } = ctx;
		await reporter.plan(planFor(epic, undefined, exhausted));

		if (ctx.abortSignal.aborted) {
			await reporter.response(`Stopped. Progress so far is on \`${record.branch}\`; delegate or reply to resume.`);
			return "stopped";
		}

		const scoped = epic.stories.filter(inScope);
		const cost = record.totalCostUsd > 0 ? ` (≈$${record.totalCostUsd.toFixed(2)} of agent usage)` : "";
		if (isEpicComplete(scoped)) {
			const all = isEpicComplete(epic.stories);
			// Commits that never reached a remote (e.g. origin was added after the stories ran).
			if (config.ralph.pushPerStory && record.branch) {
				try {
					if (await this.deps.git.needsPush(worktree, repo.baseBranch)) await this.deps.git.push(worktree, record.branch);
				} catch (err) {
					await reporter.error(`Push failed: ${String(err)}`);
				}
			}
			try {
				await this.syncPullRequest(ctx, epic, repo, worktree, all && config.ralph.markPrReadyWhenComplete);
			} catch (err) {
				log.warn(`PR sync failed: ${String(err)}`);
			}
			if (all && epic.kind !== "single" && (config.ralph.epicCompletedStateName || config.ralph.epicCompletedStateType)) {
				await linear
					.setIssueState(epic.issueId, { name: config.ralph.epicCompletedStateName, type: config.ralph.epicCompletedStateType ?? undefined })
					.catch((e: unknown) => log.warn(String(e)));
			}
			if (requestOutput) {
				const link = record.prUrl && !requestOutput.includes(record.prUrl) ? `\n\n${prLabel(record.prUrl)}: ${record.prUrl}` : "";
				await reporter.response(`${requestOutput}${link}`);
				return "completed";
			}
			const what = scoped.length === 1 ? `**${scoped[0]?.storyId}**` : `all ${scoped.length} stories of **${epic.identifier}**`;
			await reporter.response(
				`Finished ${what} on \`${record.branch}\`${cost}.${record.prUrl ? `\n\n${prLabel(record.prUrl)}: ${record.prUrl}` : ""}`,
			);
			return "completed";
		}

		if (requestOutput) await reporter.thought(requestOutput);
		await this.adoptPullRequest(ctx, repo, worktree);

		const byKey = new Map(epic.stories.map((s) => [s.key, s]));
		const isOpen = (d: string) => {
			const s = byKey.get(d);
			return !s || !isStoryDone(s);
		};
		// Outside issues that hold up the remaining in-scope stories (directly or via another story).
		const waitingOn = new Map<string, string>();
		for (const s of scoped.filter((x) => !isStoryDone(x))) {
			for (const d of s.dependsOn) {
				const ext = externalIdOf(d);
				if (ext) waitingOn.set(ext, dependencyLabel(epic, d));
			}
		}
		const blockerChain = (s: Story, seen = new Set<string>()): void => {
			for (const d of s.dependsOn) {
				const dep = byKey.get(d);
				if (!dep || isStoryDone(dep) || seen.has(d)) continue;
				seen.add(d);
				for (const dd of dep.dependsOn) {
					const ext = externalIdOf(dd);
					if (ext) waitingOn.set(ext, dependencyLabel(epic, dd));
				}
				blockerChain(dep, seen);
			}
		};
		for (const s of scoped.filter((x) => !isStoryDone(x))) blockerChain(s);
		// A focused (single-story) run can't do its sibling prerequisites itself: wait for them too.
		if (record.focusStoryKey) {
			for (const d of byKey.get(record.focusStoryKey)?.dependsOn ?? []) {
				const dep = byKey.get(d);
				if (dep?.issueId && !isStoryDone(dep) && !exhausted.has(dep.key)) waitingOn.set(dep.issueId, dep.identifier ?? dep.storyId);
			}
		}
		record.waitingOn = [...waitingOn].map(([id, identifier]) => ({ id, identifier }));

		const stuck = scoped.filter((s) => exhausted.has(s.key));
		if (!hitCap && stuck.length === 0 && record.waitingOn.length > 0) {
			const done = scoped.filter(isStoryDone).length;
			return this.park(ctx, epic, record.waitingOn, `${done}/${scoped.length} stories are done; the rest are waiting`);
		}

		const lines: string[] = [];
		if (hitCap) lines.push(`I reached the per-run iteration cap (${config.ralph.maxIterationsPerRun}).`);
		for (const s of stuck) {
			lines.push(`**${s.storyId}: ${s.title}** failed ${record.attempts[s.key]} attempts. Last problem:\n\n${tail(record.lastFeedback[s.key] ?? "unknown", 1500)}`);
		}
		const blocked = blockedStories(scoped, exhausted);
		for (const s of blocked) {
			const why = s.dependsOn.filter(isOpen).map((d) => dependencyLabel(epic, d));
			lines.push(`**${s.storyId}** is blocked by ${why.join(", ")}.`);
		}
		if (record.focusStoryKey && lines.length === 0) {
			const s = byKey.get(record.focusStoryKey);
			if (s && !isStoryDone(s)) lines.push(`**${s.storyId}** is waiting on dependencies that aren't done yet.`);
		}
		const done = scoped.filter(isStoryDone).length;
		await reporter.elicitation(
			[
				`Paused with ${done}/${scoped.length} stories complete on \`${record.branch}\`${cost}.`,
				...lines,
				record.waitingOn.length
					? `I'll also resume on my own when ${record.waitingOn.map((w) => w.identifier).join(", ")} is done.`
					: "",
				"Reply with guidance (it will be added to every story prompt) and I'll retry, or say `stop`.",
			]
				.filter(Boolean)
				.join("\n\n"),
		);
		return "awaiting_input";
	}

	/** Park the session until an outside blocker is resolved (Issue webhook or poll wakes it). */
	private async park(ctx: EngineRun, epic: Epic, blockers: Array<{ id: string; identifier: string }>, lead: string): Promise<SessionStatus> {
		ctx.record.waitingOn = blockers;
		await ctx.persist();
		await ctx.reporter.plan(planFor(epic));
		const names = blockers.map((b) => `**${b.identifier}**`).join(", ");
		await ctx.reporter.elicitation(
			`${lead} on ${names}. I'll start automatically when ${blockers.length > 1 ? "any of them is" : "it's"} done or canceled.\n\nReply \`start anyway\` to ignore the blockers, or \`stop\` to cancel.`,
		);
		return "blocked";
	}
}
